### PR TITLE
Fill in space in social buttons when options are turned off

### PR DESCRIPTION
**Pull request by nfourre**
## References

Related Issues https://github.com/consuldemocracy/consuldemocracy/issues/5489

## Objectives

Enable that social button fill empty space when options are disabled

## Visual Changes

image

## Notes
Pull request made during the Hacktoberfest.

### CODE REVIEW

**Comment by javierm** [comment]
Hi, @nfourre :smile:. Thanks for this pull request! :tada:

Looks like the linters are failing. Could you have a look? :pray:

By the way, just out of curiosity (leaving it like it is now is fine!): any reason to use a flex layout instead of the grid layout mentioned in https://github.com/consuldemocracy/consuldemocracy/issues/5489#issuecomment-2053681845? Limited browser support for `minmax`, perhaps? :thinking:

**Comment by nfourre** [comment]
Yes for sure, i update the PR to fix stylelint.

I use flexbox instead of grid layout, it's just more simple in this case.

**Comment by nfourre** [comment]
Sorry i have not fixed the stylelint whitespace error in previous PR, so I update it another.

**Review by javierm — APPROVED** [review]
@nfourre Thank you very much! :tada:

I've added an additional commit refactoring this part of the code in order to follow some conventions we follow in new code and that we haven't documented yet (sorry for that :pray:; we're working on it!).

I've also made a small change in the CSS, using `@include grid-column-gutter;` to use the same padding we usually use to add space between elements.

**Comment by javierm** [comment]
@taitus Could you have a look at these changes? :pray:

**Review by taitus — APPROVED** [review]

**Pull request merged**
